[package]
name = "rust_jni"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
hsv = "0.1.1"
itertools = "0.14.0"
jni = { version = "0.21.1", default-features = false }
num = "0.4.3"
